package com.job.manager.company.dto;

import com.job.manager.company.entity.CompanyMedia;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * Data Transfer Object for media API responses.
 * 
 * This DTO represents the complete state of a media item as returned
 * by the API. It includes all fields from the CompanyMedia entity,
 * providing clients with full information about the media.
 * 
 * The DTO pattern separates the API contract from the internal database
 * model, allowing us to modify the entity structure without breaking
 * existing API clients.
 * 
 * Used in responses for:
 * - POST /media (after creating new media)
 * - GET /media (listing all media)
 * - PUT /media/{id} (after updating media)
 */
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class CompanyMediaResponseDto {

    /**
     * Unique identifier for this media item.
     * Generated by the service when media is created.
     * Used in update and delete operations.
     */
    private String mediaId;

    /**
     * The company that owns this media.
     * Included for reference, though typically clients already know this
     * from their authentication context.
     */
    private String companyId;

    /**
     * The permanent URL where the media file is stored.
     * Clients can use this URL directly in img or video tags.
     */
    private String url;

    /**
     * The type of media: IMAGE or VIDEO.
     * Helps clients render appropriate UI components
     * (image viewer vs video player).
     */
    private CompanyMedia.MediaType mediaType;

    /**
     * Display title for the media.
     * May be null if not provided during creation.
     */
    private String title;

    /**
     * Description or caption for the media.
     * May be null if not provided during creation.
     */
    private String description;

    /**
     * Display position in the gallery.
     * Lower numbers appear first (0, 1, 2...).
     * Used for sorting media in the correct sequence.
     */
    private Integer orderIndex;

    /**
     * Visibility status of the media.
     * - true: Published and visible in public profile
     * - false: Hidden from public view
     */
    private Boolean isActive;

    /**
     * Timestamp when this media was originally uploaded.
     * Never changes after creation, useful for displaying
     * "Uploaded on..." information or sorting by recency.
     */
    private LocalDateTime uploadedAt;
}
